version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
      - NEXT_PUBLIC_WS_URL=ws://backend:8000/ws
    depends_on:
      - backend
    networks:
      - admorph-network

  backend:
    build:
      context: ./admorph_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ADMORPH_ENVIRONMENT=development
      - ADMORPH_HOST=0.0.0.0
      - ADMORPH_PORT=8000
      - ADMORPH_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      - DATABASE_URL=postgresql://admorph:${POSTGRES_PASSWORD:-admorph_password}@postgres:5432/admorph
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN:-}
      - META_APP_ID=${META_APP_ID:-}
      - META_APP_SECRET=${META_APP_SECRET:-}
      - META_AD_ACCOUNT_ID=${META_AD_ACCOUNT_ID:-}
      - SHOPIFY_STORE_URL=${SHOPIFY_STORE_URL:-}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN:-}
      - AMAZON_ACCESS_KEY_ID=${AMAZON_ACCESS_KEY_ID:-}
      - AMAZON_SECRET_ACCESS_KEY=${AMAZON_SECRET_ACCESS_KEY:-}
      - WOOCOMMERCE_URL=${WOOCOMMERCE_URL:-}
      - WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY:-}
      - WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET:-}
    volumes:
      - backend-uploads:/app/uploads
      - backend-logs:/app/logs
    networks:
      - admorph-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - admorph-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=admorph
      - POSTGRES_USER=admorph
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admorph_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - admorph-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admorph"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  admorph-network:
    driver: bridge

volumes:
  backend-uploads:
  backend-logs:
  redis-data:
  postgres-data:
